// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/incident.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/incident.go -destination=internal/service/mocks/mock_incident_repository.go -package=mocks IncidentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/shenikar/geo_broadcasting_system/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIncidentRepository is a mock of IncidentRepository interface.
type MockIncidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepositoryMockRecorder
	isgomock struct{}
}

// MockIncidentRepositoryMockRecorder is the mock recorder for MockIncidentRepository.
type MockIncidentRepositoryMockRecorder struct {
	mock *MockIncidentRepository
}

// NewMockIncidentRepository creates a new mock instance.
func NewMockIncidentRepository(ctrl *gomock.Controller) *MockIncidentRepository {
	mock := &MockIncidentRepository{ctrl: ctrl}
	mock.recorder = &MockIncidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepository) EXPECT() *MockIncidentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIncidentRepository) Create(ctx context.Context, incident *models.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIncidentRepositoryMockRecorder) Create(ctx, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIncidentRepository)(nil).Create), ctx, incident)
}

// Delete mocks base method.
func (m *MockIncidentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIncidentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIncidentRepository)(nil).Delete), ctx, id)
}

// FindActiveLocation mocks base method.
func (m *MockIncidentRepository) FindActiveLocation(ctx context.Context, lat, lon float64) ([]*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveLocation", ctx, lat, lon)
	ret0, _ := ret[0].([]*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveLocation indicates an expected call of FindActiveLocation.
func (mr *MockIncidentRepositoryMockRecorder) FindActiveLocation(ctx, lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveLocation", reflect.TypeOf((*MockIncidentRepository)(nil).FindActiveLocation), ctx, lat, lon)
}

// GetByID mocks base method.
func (m *MockIncidentRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIncidentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIncidentRepository)(nil).GetByID), ctx, id)
}

// GetIncidentFromCache mocks base method.
func (m *MockIncidentRepository) GetIncidentFromCache(ctx context.Context, id uuid.UUID) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentFromCache", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentFromCache indicates an expected call of GetIncidentFromCache.
func (mr *MockIncidentRepositoryMockRecorder) GetIncidentFromCache(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentFromCache", reflect.TypeOf((*MockIncidentRepository)(nil).GetIncidentFromCache), ctx, id)
}

// GetLocationCheckStats mocks base method.
func (m *MockIncidentRepository) GetLocationCheckStats(ctx context.Context, minutes int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationCheckStats", ctx, minutes)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationCheckStats indicates an expected call of GetLocationCheckStats.
func (mr *MockIncidentRepositoryMockRecorder) GetLocationCheckStats(ctx, minutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationCheckStats", reflect.TypeOf((*MockIncidentRepository)(nil).GetLocationCheckStats), ctx, minutes)
}

// InvalidateIncidentCache mocks base method.
func (m *MockIncidentRepository) InvalidateIncidentCache(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateIncidentCache", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateIncidentCache indicates an expected call of InvalidateIncidentCache.
func (mr *MockIncidentRepositoryMockRecorder) InvalidateIncidentCache(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateIncidentCache", reflect.TypeOf((*MockIncidentRepository)(nil).InvalidateIncidentCache), ctx, id)
}

// ListIncidents mocks base method.
func (m *MockIncidentRepository) ListIncidents(ctx context.Context, page, pageSize int) ([]*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, page, pageSize)
	ret0, _ := ret[0].([]*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockIncidentRepositoryMockRecorder) ListIncidents(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockIncidentRepository)(nil).ListIncidents), ctx, page, pageSize)
}

// SaveLocationCheck mocks base method.
func (m *MockIncidentRepository) SaveLocationCheck(ctx context.Context, check *models.LocationCheck) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLocationCheck", ctx, check)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLocationCheck indicates an expected call of SaveLocationCheck.
func (mr *MockIncidentRepositoryMockRecorder) SaveLocationCheck(ctx, check any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLocationCheck", reflect.TypeOf((*MockIncidentRepository)(nil).SaveLocationCheck), ctx, check)
}

// SetIncidentCache mocks base method.
func (m *MockIncidentRepository) SetIncidentCache(ctx context.Context, incident *models.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIncidentCache", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIncidentCache indicates an expected call of SetIncidentCache.
func (mr *MockIncidentRepositoryMockRecorder) SetIncidentCache(ctx, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIncidentCache", reflect.TypeOf((*MockIncidentRepository)(nil).SetIncidentCache), ctx, incident)
}

// Update mocks base method.
func (m *MockIncidentRepository) Update(ctx context.Context, incident *models.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIncidentRepositoryMockRecorder) Update(ctx, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIncidentRepository)(nil).Update), ctx, incident)
}

// MockIncidentService is a mock of IncidentService interface.
type MockIncidentService struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentServiceMockRecorder
	isgomock struct{}
}

// MockIncidentServiceMockRecorder is the mock recorder for MockIncidentService.
type MockIncidentServiceMockRecorder struct {
	mock *MockIncidentService
}

// NewMockIncidentService creates a new mock instance.
func NewMockIncidentService(ctrl *gomock.Controller) *MockIncidentService {
	mock := &MockIncidentService{ctrl: ctrl}
	mock.recorder = &MockIncidentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentService) EXPECT() *MockIncidentServiceMockRecorder {
	return m.recorder
}

// CheckLocation mocks base method.
func (m *MockIncidentService) CheckLocation(ctx context.Context, userID string, lat, lon float64) ([]*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLocation", ctx, userID, lat, lon)
	ret0, _ := ret[0].([]*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLocation indicates an expected call of CheckLocation.
func (mr *MockIncidentServiceMockRecorder) CheckLocation(ctx, userID, lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLocation", reflect.TypeOf((*MockIncidentService)(nil).CheckLocation), ctx, userID, lat, lon)
}

// CreateIncident mocks base method.
func (m *MockIncidentService) CreateIncident(ctx context.Context, incident *models.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncident", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIncident indicates an expected call of CreateIncident.
func (mr *MockIncidentServiceMockRecorder) CreateIncident(ctx, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncident", reflect.TypeOf((*MockIncidentService)(nil).CreateIncident), ctx, incident)
}

// DeactivateIncident mocks base method.
func (m *MockIncidentService) DeactivateIncident(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateIncident", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateIncident indicates an expected call of DeactivateIncident.
func (mr *MockIncidentServiceMockRecorder) DeactivateIncident(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateIncident", reflect.TypeOf((*MockIncidentService)(nil).DeactivateIncident), ctx, id)
}

// GetIncident mocks base method.
func (m *MockIncidentService) GetIncident(ctx context.Context, id uuid.UUID) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncident", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncident indicates an expected call of GetIncident.
func (mr *MockIncidentServiceMockRecorder) GetIncident(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncident", reflect.TypeOf((*MockIncidentService)(nil).GetIncident), ctx, id)
}

// GetStats mocks base method.
func (m *MockIncidentService) GetStats(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockIncidentServiceMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockIncidentService)(nil).GetStats), ctx)
}

// ListIncidents mocks base method.
func (m *MockIncidentService) ListIncidents(ctx context.Context, page, pageSize int) ([]*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, page, pageSize)
	ret0, _ := ret[0].([]*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockIncidentServiceMockRecorder) ListIncidents(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockIncidentService)(nil).ListIncidents), ctx, page, pageSize)
}

// UpdateIncident mocks base method.
func (m *MockIncidentService) UpdateIncident(ctx context.Context, incident *models.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncident", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncident indicates an expected call of UpdateIncident.
func (mr *MockIncidentServiceMockRecorder) UpdateIncident(ctx, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncident", reflect.TypeOf((*MockIncidentService)(nil).UpdateIncident), ctx, incident)
}
