// Code generated by MockGen. DO NOT EDIT.
// Source: internal/webhook/publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/webhook/publisher.go -destination=internal/webhook/mocks/mock_webhook_publisher.go -package=mocks WebhookPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	webhook "github.com/shenikar/geo_broadcasting_system/internal/webhook"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookPublisher is a mock of WebhookPublisher interface.
type MockWebhookPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookPublisherMockRecorder
	isgomock struct{}
}

// MockWebhookPublisherMockRecorder is the mock recorder for MockWebhookPublisher.
type MockWebhookPublisherMockRecorder struct {
	mock *MockWebhookPublisher
}

// NewMockWebhookPublisher creates a new mock instance.
func NewMockWebhookPublisher(ctrl *gomock.Controller) *MockWebhookPublisher {
	mock := &MockWebhookPublisher{ctrl: ctrl}
	mock.recorder = &MockWebhookPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookPublisher) EXPECT() *MockWebhookPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockWebhookPublisher) Publish(ctx context.Context, event webhook.WebhookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockWebhookPublisherMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockWebhookPublisher)(nil).Publish), ctx, event)
}
